<?php

return [
    'default' => env('AI_PROVIDER_DEFAULT', 'pollinations'),

    'fallbacks' => [
        'text' => ['openai'],
        'image' => ['pollinations', 'comfyui', 'openai', 'fal', 'replicate'],
        'video' => ['fal', 'replicate', 'kling', 'runway'],
        'voice' => ['elevenlabs'],
    ],

    'rate_limits' => [
        'openai' => ['max_attempts' => 60, 'decay_seconds' => 60],
        'pollinations' => ['max_attempts' => 80, 'decay_seconds' => 60],
        'kling' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'runway' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'fal' => ['max_attempts' => 30, 'decay_seconds' => 60],
        'replicate' => ['max_attempts' => 30, 'decay_seconds' => 60],
        'comfyui' => ['max_attempts' => 100, 'decay_seconds' => 60],
        'wan' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'ltx' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'minimax' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'veo' => ['max_attempts' => 20, 'decay_seconds' => 60],
        'elevenlabs' => ['max_attempts' => 40, 'decay_seconds' => 60],
    ],

    'providers' => [
        'openai' => [
            'api_key' => env('OPENAI_API_KEY'),
            'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
            'text_model' => env('OPENAI_TEXT_MODEL', 'gpt-4.1-mini'),
            'image_model' => env('OPENAI_IMAGE_MODEL', 'gpt-image-1'),
        ],
        'pollinations' => [
            'api_key' => env('POLLINATIONS_API_KEY'),
            'base_url' => env('POLLINATIONS_BASE_URL', 'https://gen.pollinations.ai'),
            'image_model' => env('POLLINATIONS_IMAGE_MODEL', 'flux'),
            'seed' => (int) env('POLLINATIONS_SEED', 0),
            'enhance' => env('POLLINATIONS_ENHANCE', false),
            'timeout' => (int) env('POLLINATIONS_TIMEOUT', 180),
        ],
        'comfyui' => [
            'base_url' => env('COMFYUI_BASE_URL', 'http://127.0.0.1:8188'),
            'poll_interval_ms' => (int) env('COMFYUI_POLL_INTERVAL_MS', 1500),
            'max_poll_attempts' => (int) env('COMFYUI_MAX_POLL_ATTEMPTS', 180),
            'flux_checkpoint' => env('COMFYUI_FLUX_CHECKPOINT', 'flux1-schnell-fp8.safetensors'),
            'sd15_checkpoint' => env('COMFYUI_SD15_CHECKPOINT', 'v1-5-pruned-emaonly.safetensors'),
            'flux_steps' => (int) env('COMFYUI_FLUX_STEPS', 4),
            'flux_cfg' => (float) env('COMFYUI_FLUX_CFG', 1),
            'flux_sampler' => env('COMFYUI_FLUX_SAMPLER', 'euler'),
            'flux_scheduler' => env('COMFYUI_FLUX_SCHEDULER', 'simple'),
            'sd15_steps' => (int) env('COMFYUI_SD15_STEPS', 24),
            'sd15_cfg' => (float) env('COMFYUI_SD15_CFG', 7),
            'sd15_sampler' => env('COMFYUI_SD15_SAMPLER', 'dpmpp_2m'),
            'sd15_scheduler' => env('COMFYUI_SD15_SCHEDULER', 'karras'),
        ],
        'kling' => [
            'api_key' => env('KLING_API_KEY'),
            'base_url' => env('KLING_BASE_URL', 'https://api.klingai.com'),
            'video_model' => env('KLING_VIDEO_MODEL', 'kling-v1-6'),
        ],
        'fal' => [
            'api_key' => env('FAL_KEY', env('FAL_API_KEY')),
            'base_url' => env('FAL_BASE_URL', 'https://queue.fal.run'),
            'poll_interval_ms' => (int) env('FAL_POLL_INTERVAL_MS', 2500),
            'max_poll_attempts' => (int) env('FAL_MAX_POLL_ATTEMPTS', 90),
            'image_model' => env('FAL_IMAGE_MODEL', 'fal-ai/flux-pro/v1.1'),
            'video_model' => env('FAL_VIDEO_MODEL', env('FAL_KLING_MODEL', 'fal-ai/kling-video/v2.1/master/text-to-video')),
            'video_models' => [
                'kling' => env('FAL_KLING_MODEL', 'fal-ai/kling-video/v2.1/master/text-to-video'),
                'wan' => env('FAL_WAN_MODEL', 'fal-ai/wan/v2.2-a14b/text-to-video'),
                'ltx' => env('FAL_LTX_MODEL', 'fal-ai/ltx-video/13b-098-distilled'),
                'minimax' => env('FAL_MINIMAX_MODEL', 'fal-ai/minimax/video-01'),
                'veo' => env('FAL_VEO_MODEL', 'fal-ai/veo3'),
            ],
        ],
        'replicate' => [
            'api_key' => env('REPLICATE_API_TOKEN'),
            'base_url' => env('REPLICATE_BASE_URL', 'https://api.replicate.com'),
            'poll_interval_ms' => (int) env('REPLICATE_POLL_INTERVAL_MS', 3000),
            'max_poll_attempts' => (int) env('REPLICATE_MAX_POLL_ATTEMPTS', 90),
            'image_model' => env('REPLICATE_IMAGE_MODEL'),
            'image_version' => env('REPLICATE_IMAGE_VERSION'),
            'video_model' => env('REPLICATE_VIDEO_MODEL'),
            'video_version' => env('REPLICATE_VIDEO_VERSION'),
            'video_models' => [
                'kling' => env('REPLICATE_KLING_MODEL'),
                'wan' => env('REPLICATE_WAN_MODEL'),
                'ltx' => env('REPLICATE_LTX_MODEL'),
                'minimax' => env('REPLICATE_MINIMAX_MODEL'),
                'veo' => env('REPLICATE_VEO_MODEL'),
            ],
        ],
        'wan' => [
            'api_key' => env('WAN_API_KEY'),
            'base_url' => env('WAN_BASE_URL'),
            'video_model' => env('WAN_VIDEO_MODEL', 'wan-2.1'),
        ],
        'ltx' => [
            'api_key' => env('LTX_API_KEY'),
            'base_url' => env('LTX_BASE_URL'),
            'video_model' => env('LTX_VIDEO_MODEL', 'ltx-video'),
        ],
        'minimax' => [
            'api_key' => env('MINIMAX_API_KEY'),
            'base_url' => env('MINIMAX_BASE_URL'),
            'video_model' => env('MINIMAX_VIDEO_MODEL', 'video-01'),
        ],
        'veo' => [
            'api_key' => env('VEO_API_KEY'),
            'base_url' => env('VEO_BASE_URL'),
            'video_model' => env('VEO_VIDEO_MODEL', 'veo-3'),
        ],
        'runway' => [
            'api_key' => env('RUNWAY_API_KEY'),
            'base_url' => env('RUNWAY_BASE_URL', 'https://api.dev.runwayml.com'),
            'api_version' => env('RUNWAY_API_VERSION', '2024-11-06'),
            'video_model' => env('RUNWAY_VIDEO_MODEL', 'gen4.5'),
            'image_model' => env('RUNWAY_IMAGE_MODEL', 'gen4_image'),
        ],
        'elevenlabs' => [
            'api_key' => env('ELEVENLABS_API_KEY'),
            'base_url' => env('ELEVENLABS_BASE_URL', 'https://api.elevenlabs.io/v1'),
            'voice_model' => env('ELEVENLABS_MODEL', 'eleven_multilingual_v2'),
            'default_voice_id' => env('ELEVENLABS_DEFAULT_VOICE_ID'),
            'voices' => [
                'female_south' => env('ELEVENLABS_VOICE_FEMALE_SOUTH'),
                'male_north' => env('ELEVENLABS_VOICE_MALE_NORTH'),
                'ai_en' => env('ELEVENLABS_VOICE_AI_EN'),
            ],
        ],
    ],
];
