<?php

return [
    'items' => [
        [
            'section' => 'workspace',
            'section_label_key' => 'messages.erp.sidebar.workspace',
            'section_icon' => 'users',
            'section_sort_order' => 10,
            'label_key' => 'messages.erp.sidebar.overview',
            'route' => 'dashboard',
            'active_patterns' => ['dashboard'],
            'icon' => 'grid',
            'sort_order' => 10,
            'is_admin_only' => false,
        ],
        [
            'section' => 'workspace',
            'section_label_key' => 'messages.erp.sidebar.workspace',
            'section_icon' => 'users',
            'section_sort_order' => 10,
            'label_key' => 'messages.erp.sidebar.timekeeping',
            'route' => 'erp.timekeeping',
            'active_patterns' => ['erp.timekeeping'],
            'icon' => 'clock',
            'sort_order' => 20,
            'is_admin_only' => false,
        ],
        [
            'section' => 'workspace',
            'section_label_key' => 'messages.erp.sidebar.workspace',
            'section_icon' => 'users',
            'section_sort_order' => 10,
            'label_key' => 'messages.erp.sidebar.leaves',
            'route' => 'erp.leaves',
            'active_patterns' => ['erp.leaves'],
            'icon' => 'file',
            'sort_order' => 30,
            'is_admin_only' => false,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.contracts',
            'route' => 'erp.contracts',
            'active_patterns' => ['erp.contracts'],
            'icon' => 'cart',
            'sort_order' => 10,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.bom',
            'route' => 'erp.bom',
            'active_patterns' => ['erp.bom'],
            'icon' => 'factory',
            'sort_order' => 20,
            'is_admin_only' => true,
            'is_enabled' => false,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.products',
            'route' => 'products.index',
            'active_patterns' => ['products.*'],
            'icon' => 'box',
            'sort_order' => 30,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.inventory',
            'route' => 'erp.inventory',
            'active_patterns' => ['erp.inventory'],
            'icon' => 'warehouse',
            'sort_order' => 40,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.purchase_orders',
            'route' => 'erp.purchase-orders',
            'active_patterns' => ['erp.purchase-orders'],
            'icon' => 'truck',
            'sort_order' => 50,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.stock_report',
            'route' => 'erp.stock-report',
            'active_patterns' => ['erp.stock-report'],
            'icon' => 'report',
            'sort_order' => 60,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.payroll',
            'route' => 'erp.payroll',
            'active_patterns' => ['erp.payroll'],
            'icon' => 'dollar',
            'sort_order' => 70,
            'is_admin_only' => true,
        ],
        [
            'section' => 'business',
            'section_label_key' => 'messages.erp.sidebar.business_group',
            'section_icon' => 'warehouse',
            'section_sort_order' => 20,
            'label_key' => 'messages.erp.sidebar.analytics',
            'route' => 'erp.analytics',
            'active_patterns' => ['erp.analytics'],
            'icon' => 'pulse',
            'sort_order' => 80,
            'is_admin_only' => true,
        ],
        [
            'section' => 'marketing',
            'section_label_key' => 'messages.erp.sidebar.marketing_group',
            'section_icon' => 'megaphone',
            'section_sort_order' => 25,
            'label_key' => 'messages.erp.sidebar.content_ai',
            'route' => 'marketing.content.index',
            'active_patterns' => [
                'marketing.index',
                'marketing.content.*',
            ],
            'icon' => 'pen',
            'sort_order' => 10,
            'is_admin_only' => true,
        ],
        [
            'section' => 'marketing',
            'section_label_key' => 'messages.erp.sidebar.marketing_group',
            'section_icon' => 'megaphone',
            'section_sort_order' => 25,
            'label_key' => 'messages.erp.sidebar.ai_images',
            'route' => 'marketing.images',
            'active_patterns' => ['marketing.images*'],
            'icon' => 'image',
            'sort_order' => 20,
            'is_admin_only' => true,
        ],
        [
            'section' => 'marketing',
            'section_label_key' => 'messages.erp.sidebar.marketing_group',
            'section_icon' => 'megaphone',
            'section_sort_order' => 25,
            'label_key' => 'messages.erp.sidebar.brain_ai',
            'route' => 'marketing.brain.index',
            'active_patterns' => ['marketing.brain.*'],
            'icon' => 'database',
            'sort_order' => 30,
            'is_admin_only' => true,
        ],
        [
            'section' => 'system',
            'section_label_key' => 'messages.erp.sidebar.system_group',
            'section_icon' => 'settings',
            'section_sort_order' => 30,
            'label_key' => 'messages.erp.sidebar.user_management',
            'route' => 'users.index',
            'active_patterns' => ['users.*'],
            'icon' => 'users',
            'sort_order' => 10,
            'is_admin_only' => false,
        ],
        [
            'section' => 'system',
            'section_label_key' => 'messages.erp.sidebar.system_group',
            'section_icon' => 'settings',
            'section_sort_order' => 30,
            'label_key' => 'messages.erp.sidebar.roles',
            'route' => 'roles.index',
            'active_patterns' => ['roles.*'],
            'icon' => 'shield',
            'sort_order' => 15,
            'is_admin_only' => true,
        ],
        [
            'section' => 'system',
            'section_label_key' => 'messages.erp.sidebar.system_group',
            'section_icon' => 'settings',
            'section_sort_order' => 30,
            'label_key' => 'messages.erp.sidebar.settings',
            'route' => 'settings.index',
            'active_patterns' => ['settings.*'],
            'icon' => 'settings',
            'sort_order' => 20,
            'is_admin_only' => false,
        ],
    ],
];
